mate-desktop/mate-terminal

- src/terminal-window.c
due to the tricky macro magic, a piece of code containing a function
that doesn't exist in GTK+3 version of VTE hasn't been compiled into
the stable versions of mate-terminal. now we bumped version to 1.13.0,
that code got into build, and the build broke.
this commit should fix it.
> fix GTK+3 build when our version is unstable (e.g. 1.13.x)

- src/terminal-options.c
- src/terminal-screen-container.c
- src/terminal-screen.c
- src/terminal-window.c
In Gtk 3.20 they changed what geometry_widget does in gtk_window_set_geometry_hints(), so I made it so sizes are calculated for the whole window, not only the terminal widget.
> Fix terminal sizes on Gtk 3.20

- src/terminal-screen.c
this kills warnings with newer vte.
taken from (but adjusted):
https://git.gnome.org/browse/gnome-terminal/commit/?id=9e0ea90
```
(mate-terminal:3190): Vte-WARNING **: (vtegtk.cc:1735):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
(mate-terminal:3190): Vte-WARNING **: (vtegtk.cc:1735):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
```
@monsta 
please test with gtk2
> screen: Compile dingu regexes with MULTILINE option

- src/terminal-tab-label.c
fixes https://github.com/mate-desktop/mate-terminal/issues/131
thanks to @egmontkob for the patch:
https://git.gnome.org/browse/gnome-terminal/commit/?id=f65261a0b5d03658be3acb439976fd8af6fa28ea
@dpblnt @raveit65 @lukefromdc @XRevan86 @sc0w
I could reproduce it only in Mint 18 (GTK+ 3.18.9, VTE 0.42.5) and the fix works there, but if you can't reproduce it in your systems, please check that there are no regressions - just in case.
> fix crash after detaching tab and then changing its title

- src/terminal-window.c
based on gnome-terminal commit:
https://git.gnome.org/browse/gnome-terminal/commit/?id=abb2018a702adfc57831aea9ebb5c513b9c8bbbd
Fixes #152 
@raveit65 @monsta 
I think now is solved
> Make dropped tab active

- src/terminal-screen.c
- src/terminal-window.c
Fixes partially #149
It works closing mate-terminal, and closing a tab with click on X
Don't works with middle button over a tab
I will investigate that
By the moment, I think we can merge this
> screen: Update for vte API

- src/terminal-window.c
Fixes:
If we are on a tab, and we make middle click on another tab,
it doesn't show the confirm close dialog if there is a foreground process
> middle click on a tab: Better behavior

- src/terminal-window.c
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1398234
I can't reproduce the issue, but the user affected confirm, this solution works
The issue:
>  Milan Crha
> 
> When I run multiple mate-terminals and close one of them then all are currently running instances are closed too. That's a regression and a bad behaviour, the terminal windows are independent.
> 
> Steps:
> a) run mate-terminal
> b) in there run: mate-terminal &
> c) in either of the two press either Ctrl+D or execute: exit
> 
> Both windows are closed, but only the one where the c) had been done should be closed. Note, I run the terminals from a custom .desktop file.
> 
> This is with mate-terminal-1.16.1-2.fc25.x86_64
> 
> Downgrading to mate-terminal-1.16.1-1.fc25.x86_64 fixes the issue.
> call gtk_notebook_detach_tab only if the tab is detached

- src/find-dialog.ui
- src/profile-manager.ui
- src/profile-preferences.ui
this causes runtime warnings about transient parent because these
dialogs get mapped too early, before gtk_window_set_transient_for
is called in the code.
affected dialogs: find, profile manager, profile prefs
this is an alternative to https://github.com/mate-desktop/mate-terminal/pull/163.
> don't mark dialogs as visible in .ui files

- src/terminal-window.c
Fixes #171
This fix needs to test in wayland too, to know if the commit https://github.com/mate-desktop/mate-terminal/commit/575fc201f08cefecf469344ba3b2b02f1174fbc1 is working after this
> Fix: Double click with right button causes Xorg to crash

- src/terminal-window.c
avoid deprecated:
gdk_screen_get_monitor_geometry
gdk_screen_get_monitor_at_window
> gtk 3.22: avoid deprecated gdk_screen_get_monitor... functions:

- src/org.mate.terminal.gschema.xml.in
- src/terminal-accels.c
- src/terminal-window.c
Closes https://github.com/mate-desktop/mate-terminal/issues/191
EDIT: finally I use [control+shift+a], because [control+shift] seems to be the standard in all menus in mate-terminal. Anyway, it can be changed with this PR, in **edit -> keyboard shortcuts**
> add "select all" keyboard shortcut: [control] + [shift] + [A]

- src/find-dialog.ui
This fixes tabbing with the keyboard in find dialog.
> find-dialog.ui: fix keyboard selection

- src/terminal-window.c
This commit reverts:
https://github.com/mate-desktop/mate-terminal/commit/5c6f10892aed32bf7c450962119f65c470898d6d
And it applies an alternative to fix the deprecated functions:
gdk_screen_get_width
gdk_screen_get_height
> WidthOfScreen and HeightOfScreen implementation

- src/profile-editor.c
See https://bugzilla.gnome.org/768850 for the bug description and steps to reproduce.
> profile-editor: properly initialize the first palette color

- src/Makefile.am
- src/terminal-screen.c
closes https://github.com/mate-desktop/mate-terminal/issues/209
taken from:
https://git.gnome.org/browse/gnome-terminal/commit/?id=a0ecd018f070b96a6ca2ff778ddda0f7fde5b847
https://git.gnome.org/browse/gnome-terminal/commit/?id=1d5c1b6ca6373c1301494edbc9e43c3e6a9c9aaf
> screen: stop setting TERM and COLORTERM environment variables

- src/terminal-app.c
- src/terminal-window.c
The expected with this PR: the same icons like before
Note: I think the translations are affected, so, this is not for 1.20
> avoid deprecated GtkStock

- src/terminal-app.c
in the "delete profile" dialog:
how to test:
see the GtkImage properties `icon-name`, `stock` and `storage-type` in gtk-inspector without / with the PR
The expected: the same look and behavior like before
> terminal-app: avoid gtk_dialog_add_buttons with stock ids

- src/terminal-window.c
Fixes https://github.com/mate-desktop/mate-terminal/issues/233
In the tests, make sure the commits https://github.com/mate-desktop/mate-terminal/commit/294ce367b2d376bb4b53017136c82af94a15026e https://github.com/mate-desktop/mate-terminal/commit/7ebc9d18b3abd2d1f3baa3a8e80b1fd9cb6e0621 are working
> terminal-window: Fix: Session dbus daemon saturated

- src/terminal-screen.c
This reverts commit e1b834a2bf684ac4a7d4b33fbf216d65896889c6.
Fixes https://github.com/mate-desktop/mate-terminal/issues/240
> Revert "fix setting transparency issue when used in GNOME3"

- src/terminal-screen.c
With this PR, this setting must works as before:
`edit -> profile preferences -> colors -> use colors from system theme`
> term-screen: avoid deprecated 'gtk_style_context_get_background_color'

- help/C/index.docbook
Window title is defined by Initial title setting
> Help - Window title when MATE Terminal is started for first time

- src/terminal-window.c
When changing tabs, the function that updates the Copy menu popup entry is called. Within this function there's also a call to update the selected text in the clipboard, which means that the clipboard data is lost when changing tabs.
This patch separates those functions to retain the data in the clipboard.
Fixes #239
> Retain copied selection when changing tabs

- help/C/index.docbook
- help/C/legal.xml
To upgrade the manual:
```shell
wget https://docbook.org/xml/5.0.1/tools/db4-upgrade.xsl
xsltproc --output index-new.docbook db4-upgrade.xsl index.docbook
xsltproc --output legal-new.xml db4-upgrade.xsl legal.xml
```
To validate the manual:
```shell
wget https://docbook.org/xml/5.0.1/rng/docbookxi.rng
jing docbookxi.rng index.docbook
```
To view the manual:
```shell
yelp file:///full_path/index.docbook
```
> Upgrade the manual to docbook 5.0

- src/org.mate.terminal.gschema.xml.in
- src/terminal-window.c
As a followup #149 this fixes the behavior of the code to match the
description of the respective gsettings entry "confirm-window-close".
Said entry is also updated to reflect the change added in #149.
No changes to the gsettings handling were made thus only users
who have "confirm-window-close" turned on already will see the
new behavior.
> Show confirmation dialog if there are multiple open tabs on closing

- configure.ac
- mate-terminal.appdata.xml.in
- src/terminal-window.c
Now the official web site is https://mate-desktop.org/.
> Change url project's website

- src/terminal-screen.c
- src/terminal-window.c
- src/terminal.c
`find . -regextype posix-extended -regex '.*\.(c|h|ac)' -exec sed --in-place 's/[[:space:]]\+$//' {} \+`
like rbuj do on [https://github.com/mate-desktop/mate-control-center/pull/463](https://github.com/mate-desktop/mate-control-center/pull/463).
> Remove trailing whitespaces

- .travis.yml
- src/terminal-tabs-menu.c
- src/terminal-window.c
They can't be replaced in Gtk-3 without removing icons from menu.
Please review.
> Surpress gtk action build warnings

- src/terminal-app.c
```
terminal-app.c:152:26: warning: passing argument 2 of ‘terminal_app_profile_list_notify_cb’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
terminal-app.c:153:29: warning: passing argument 2 of ‘terminal_app_default_profile_notify_cb’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
terminal-app.c:155:27: warning: passing argument 2 of ‘terminal_app_encoding_list_notify_cb’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
terminal-app.c:143:28: warning: passing argument 2 of ‘terminal_app_system_font_notify_cb’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
terminal-app.c:149:35: warning: passing argument 2 of ‘terminal_app_enable_menu_accels_notify_cb’ discards ‘const’ …
```
> terminal-app: remove -Wdiscarded-qualifiers warnings

- src/terminal-screen.c
> Avoid NULL pointer dereference in terminal_screen_child_exited

- src/terminal-screen.c
Fixes the warning:
`** (mate-terminal:45473): CRITICAL **: 01:32:55.425: terminal_window_remove_screen: assertion 'gtk_widget_get_toplevel (GTK_WIDGET (screen)) == GTK_WIDGET (window)' failed`
I just added the same changes of https://github.com/mate-desktop/mate-terminal/pull/316 in other place, to fix the warnings.
@rbuj please test / review
> terminal-screen: Fix warning when closing window

- src/terminal-app.c
- src/terminal-app.h
- src/terminal-encoding.c
```
/usr/bin/ld: mate_terminal-terminal-accels.o:(.bss+0x0): multiple definition of `settings_global'; mate_terminal-terminal.o:(.bss+0x0): first defined here
/usr/bin/ld: mate_terminal-terminal-app.o:(.bss+0x0): multiple definition of `settings_global'; mate_terminal-terminal.o:(.bss+0x0): first defined here
/usr/bin/ld: mate_terminal-terminal-encoding.o:(.bss+0x0): multiple definition of `settings_global'; mate_terminal-terminal.o:(.bss+0x0): first defined here
/usr/bin/ld: mate_terminal-terminal-options.o:(.bss+0x0): multiple definition of `settings_global'; mate_terminal-terminal.o:(.bss+0x0): first defined here
/usr/bin/ld: mate_terminal-terminal-profile.o:(.bss+0x0): multiple definition of `settings_global'; mate_terminal-terminal.o:(.bss+0x0): first defined here
/usr/bin/ld: …
```
> Fix build using gcc 10 -fno-common flag

- src/terminal-screen.c
Turns out the error in term spawn callback doesn't have to be released and the one that can pop up in get_child_command gets freed in terminal_screen_launch_child_cb all right.
This should fix the crash mentioned in #312, at least it does so for a non-default profile with a bad command.
> terminal-screen: prevent crash on bad term spawn due to redundant frees

- src/terminal-screen.c
> fix url highlighting due to deprecation of vte_terminal_match_add_gregex

- src/terminal-window.c
> terminal-window: show VTE version in about dialog

- src/terminal-screen.c
- src/terminal-search-dialog.c
- src/terminal-search-dialog.h
- src/terminal-window.c
The deprecated regexpg function from vte also broken search in the terminal.
Replace with searches based on VteRegexp.
> fix searching in terminal window

- src/terminal-window.c
> terminal-window: expand the content of the comment on about dialog

- src/terminal-encoding.c
Test
```
$ ./autogen.sh --prefix=/usr --enable-compile-warnings=maximum --enable-debug && make &> make.log
$ grep -A 2 Wformat make.log 
```
Removed warnings
```
terminal-encoding.c:251:27: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘gsize’ {aka ‘long unsigned int’} [-Wformat=]
251 |                           " output \"%s\" bytes read %u written %u\n",
|                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
terminal-encoding.c:251:27: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘gsize’ {aka ‘long unsigned int’} [-Wformat=]
251 |                           " output \"%s\" bytes read %u written %u\n",
|                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
```
> terminal-encoding: Remove -Wformat warning

- src/profile-editor.c
```
profile-editor.c:489:45: warning: implicit conversion from ‘enum <anonymous>’ to ‘GtkEntryIconPosition’ [-Wenum-conversion]
489 |   gtk_entry_set_icon_from_icon_name (entry, GTK_PACK_END, NULL);
|                                             ^~~~~~~~~~~~
profile-editor.c:495:45: warning: implicit conversion from ‘enum <anonymous>’ to ‘GtkEntryIconPosition’ [-Wenum-conversion]
495 |   gtk_entry_set_icon_from_icon_name (entry, GTK_PACK_END, "dialog-warning");
|                                             ^~~~~~~~~~~~
profile-editor.c:498:43: warning: implicit conversion from ‘enum <anonymous>’ to ‘GtkEntryIconPosition’ [-Wenum-conversion]
498 |   gtk_entry_set_icon_tooltip_text (entry, GTK_PACK_END, tooltip);
|                                           ^~~~~~~~~~~~
```
> profile-editor: Remove enum conversion warnings

- src/profile-editor.c
- src/profile-editor.h
Based on:
- https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5
- https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188
> terminal_profile_edit_dialog_page_scroll_event_cb is only used in profile-editor.c

- src/terminal-screen.c
- src/terminal-window.c
```
terminal-screen.c:1185:53: warning: conversion from 'double' to 'gint' {aka 'int'} may change value [-Wfloat-conversion]
1185 |                                    priv->font_scale *
|                                    ~~~~~~~~~~~~~~~~~^
--
terminal-window.c:2939:59: warning: conversion from 'gdouble' {aka 'double'} to 'int' may change value [-Wfloat-conversion]
2939 |         tab_clicked = find_tab_num_at_pos (notebook, event->x_root, event->y_root);
|                                                      ~~~~~^~~~~~~~
terminal-window.c:2939:74: warning: conversion from 'gdouble' {aka 'double'} to 'int' may change value [-Wfloat-conversion]
2939 |         tab_clicked = find_tab_num_at_pos (notebook, event->x_root, event->y_root);
| …
```
> Remove -Wfloat-conversion warnings

- src/profile-editor.c
```
profile-editor.c:540:16: warning: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
540 |  for (i = 0; i < G_N_ELEMENTS (color_schemes); ++i)
|                ^
```
> profile-editor: Fix -Wsign-compare warning

- mate-terminal.desktop.in.in
```
$ desktop-file-validate mate-terminal.desktop 
mate-terminal.desktop: hint: value "System;GTK;Utility;TerminalEmulator;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
```
> Fix desktop file validation warning

- Makefile.am
- configure.ac
- mate-terminal.appdata.xml.in.in
- meson.build
- po/POTFILES.in
- src/terminal-window.c
Test:
```
$ grep PACKAGE_URL config.h
#define PACKAGE_URL "https://mate-desktop.org"
$ grep homepage mate-terminal.appdata.xml
<url type="homepage">https://mate-desktop.org</url>
```
- Use bottom-up pattern instead of up-down for replacing the suffix at the end of file names as follows (Makefile.am):
usage:
```
$(var:suffix=replacement)
```
before:
```
appdata_in_files = mate-terminal.appdata.xml.in
appdata_DATA = $(appdata_in_files:.xml.in=.xml)
```
after:
```
appdata_DATA = mate-terminal.appdata.xml
appdata_in_files = $(appdata_DATA:.xml=.xml.in)
appdata_in_in_files = $(appdata_in_files:.xml.in=.xml.in.in)
```
> build: Use PACKAGE_URL variable

- src/terminal-window.c
```
terminal-window.c:1875:9: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
terminal-window.c:1876:9: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
terminal-window.c:1877:9: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
terminal-window.c:1878:9: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct _GtkActionEntry'} [-Wmissing-field-initializers]
terminal-window.c:1879:9: warning: missing initializer for field 'accelerator' of 'GtkActionEntry' {aka 'const struct …
```
> terminal-window: Remove -Wmissing-field-initializers warnings

- meson.build
- fixes building with meson-0.62.0
- fixes https://github.com/mate-desktop/mate-terminal/issues/411
look here for more details.
With meson-0.62.0 this deprecation warning will cause an error.
`DEPRECATION: i18n.merge_file does not take any positional arguments.
This will become a hard error in the next Meson release.`
> meson build: drop desktop-file argument

- src/terminal-encoding.c
- src/terminal-window.c
```
git submodule init
git submodule update --recursive --remote
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
```
terminal-encoding.c:162:49: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
encoding->valid = encoding->validity_checked = force_valid;
~ ^~~~~~~~~~~
terminal-encoding.c:163:24: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
encoding->is_custom = is_custom;
~ ^~~~~~~~~
--
terminal-window.c:2728:29: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') …
```
> Fix implicit conversion changes signedness: 'gboolean' to 'guint'

- src/terminal-profile.c
Fix global-buffer-overflow when profiling the code with AddressSanitizer
```
Configure summary:
mate-terminal 1.26.0
====================
prefix:                 /usr
source code location:   .
compiler:               gcc
cflags:                 -ggdb3 -O0 -fsanitize=address -g -O0
warning flags:          -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wno-unused-parameter -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes
linker flags:           
smclient support:       no
s/key support:          yes
Now type `make' to compile mate-terminal
```
```
AddressSanitizer: global-buffer-overflow on address 0x00000047a548 at pc 0x7f7a468dcb10 bp 0x7fff945136c0 sp …
```
> terminal-profile: fix initialization for default colors

- src/terminal.c
```
terminal.c:247:2: warning: missing field 'padding' initializer [-Wmissing-field-initializers]
};
^
```
> terminal: fix build warning about missing field initializer

- src/terminal-window.c
Remove the cppcheck warning below:
```
cppcheck --enable=all --quiet .
```
```
mate-terminal/src/terminal-window.c:3575:20: style: Variable 'do_confirm' is assigned a value that is never used. [unreadVariable]
do_confirm = FALSE;
^
```
> terminal-window: Variable 'do_confirm' is assigned a value that is never used

- src/terminal-window.c
This fixes an issue when a monospace font is displayed instead of a proper one in mate-terminal context (right-click) menu. This PR tries to bring a fix from Ubuntu to the upstream.
This fixes: https://github.com/mate-desktop/mate-terminal/issues/407
Also see a number of related bug reports:
https://bugs.launchpad.net/ubuntu/+source/mate-terminal/+bug/1955505
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998856
https://groups.google.com/g/linux.debian.bugs.dist/c/Xa9ZBXh_1nE
https://bugzilla.redhat.com/show_bug.cgi?id=2160523
> Add GTK Style Class to a context (right-click) menu

- src/terminal-profile.c
build command:
```
CC=clang CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" ./autogen.sh --prefix=/usr --enable-debug  --enable-compile-warnings=maximum && make &> make.log && sudo make install
```
build warnings:
```
terminal-profile.c:1289:69: warning: implicit conversion turns string literal into bool: 'char [11]' to '_Bool' [-Wstring-conversion]
TERMINAL_PROFILE_PROPERTY_BOOLEAN (ALLOW_BOLD, DEFAULT_ALLOW_BOLD, KEY_ALLOW_BOLD);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
terminal-profile.c:92:24: note: expanded from macro 'KEY_ALLOW_BOLD'
#define KEY_ALLOW_BOLD "allow-bold"
^~~~~~~~~~~~
--
terminal-profile.c:1290:91: warning: implicit conversion turns string literal into bool: 'char [22]' to '_Bool' [-Wstring-conversion] …
```
> terminal-profile: fix warning -Wstring-conversion

- src/terminal-screen.c
- src/terminal-window.c
Addresses #432 and borrows liberally from the [transparency patch](https://aur.archlinux.org/cgit/aur.git/tree/transparency.patch?h=gnome-terminal-transparency) in the AUR `gnome-terminal-transparency` package. Credit to the developers and patch collectors for that particular changeset.
A fix for this invoking `gtk_widget_set_app_paintable` was pushed up in e1b834a but rolled back due to the side effect of producing a transparent menu bar in Compiz (see #240). The current fix produces expected behavior in Marco, but produces visual composited artifacts in Mutter and Muffin.
This PR adds restores the invocation of `gtk_widget_set_app_paintable` while adding handling to explicitly draw the frame and background of the terminal window to prevent them from rendering as transparent. It also …
> Fix screen widget artifacts with Mutter-based WMs when transparent terminal background is enabled

- src/terminal-screen.c
*Otherwise x11-only apps in wayland can't connect to xwayland
*Fix https://github.com/mate-desktop/mate-terminal/issues/423
> Do not set DISPLAY, inherit it instead

- src/terminal-window.c
Allow the user to change the title of a tab by double-clicking it.
This closes #436.
> Double-click tab to set title

- src/terminal-window.c
The `uris_as_paths` member, which is set to `true` when the paste command has been triggered by the **Paste Filenames** action, was being checked too late: a file URI was ultimately being entered to the terminal, as opposed to the expected plain text version.
Test plan:
- Copy a file in Caja, or in any other file explorer that inserts the `text/uri-list` and `text/plain` MIME formats into the clipboard.
- Paste the file in a MATE Terminal either via `Ctrl+Shift+V`, or via the **Paste** action in the context menu.
Without this change, a file URI is entered. For example:
```
file:///home/jane.doe/my%20pictures/foo%20bar.jpg
```
With this change, a regular filepath [that the filesystem can recognize] is pasted. For example:
```
/home/jane.doe/my pictures/foo bar.jpg
```
Note that the …
> Avoid unprocessed file URIs being pasted to the terminal.

- src/terminal-window.c
It seems Wayland-based window managers provide additional decorations that we're not tracking in our "preferred size" computations. This means every geometry update shrinks the window by a bit.
Factor in the allocated dimensions, not just the preferred ones.
Borrows some ideas from
https://bugzilla.gnome.org/show_bug.cgi?id=769898
I also drop a few unused values leftover from gnome-terminal.
Fixes #350
> terminal-window: Factor CSDs into geometry hints

- src/terminal-window.c
Code by jankratochvil to limit effect of commit accounting for CSD dimensions to wayland sessions only as it causes problems in x11 sessions with resizing the terminal and blocks displaying the dimensions it is being resized to otherwise
> Do not suppress resize hints on X11
