- README
Just fixed a typo in the README file.
> fixed typo

- src/encodings-dialog.ui
- src/find-dialog.ui
- src/keybinding-editor.ui
- src/profile-manager.ui
- src/profile-new-dialog.ui
- src/profile-preferences.ui
- src/skey-challenge.ui
- src/terminal-app.c
- src/terminal-screen.c
> deprecations

- src/terminal-app.c
- src/terminal-screen.c
- src/terminal-window.c
- src/terminal-window.h
> Add back --geometry positioning support

- src/terminal-window.c
Fixes #155
I adapted the bl0ckeduser patch to the master branch
> Implement middle click tab closing

- src/terminal-window.c
Fixes https://github.com/mate-desktop/mate-terminal/issues/199
> avoid deprecated vte_terminal_search_get_gregex

- src/profile-editor.c
- src/terminal-screen.c
Only in opaque and tiled mode. No "scrolling background" feature. #119
> Support background images with VTE3

- src/org.mate.terminal.gschema.xml.in
- src/terminal-window.c
Closes https://github.com/mate-desktop/mate-terminal/issues/184
> middle click on a tab: add the gsettings key to enable the feature

- src/terminal-window.c
> terminal-window: replace deprecated gtk_menu_popup

- help/C/index.docbook
commit https://github.com/mate-desktop/mate-terminal/commit/29536a9f07125091f9a06c435b3e9acf42e26968
> Help - TERM=xterm-256color

- src/terminal-app.c
- src/terminal-options.c
- src/terminal-options.h
See https://github.com/mate-desktop/mate-terminal/commit/3f374d57879f6217acebe4e37b0c61bc9991eb7a
> warning: Value stored to 'screen_number' is never read

- src/terminal-screen.c
> Explicitly enable bright bold to match new VTE versions

- src/terminal-window.c
> terminal-window: "utilities-terminal" icon with "Open Terminal"

- src/terminal-window.c
Gsettings needs to be freed
I the tests, make sure these gsetting keys are working:
- middle click to close tabs
- ctrl+tab ctrl+shift+tab to switch tabs
- confirmation dialog on close window
> terminal-window: Fix memory leak

- src/terminal-app.c
- src/terminal-app.h
- src/terminal-window.c
> terminal-window: avoid to make new GSettings in every new window

- src/terminal-window.c
> add icons to "open tab" and "close window/tab" in popup menu

- po/POTFILES.in
- src/Makefile.am
- src/confirm-close-dialog.ui
- src/terminal-window.c
- src/terminal.gresource.xml
> Add confirm-close-dialog.ui

- po/POTFILES.in
- src/Makefile.am
- src/set-title-dialog.ui
- src/terminal-window.c
- src/terminal.gresource.xml
> Add set-title-dialog.ui

- configure.ac
- src/Makefile.am
- src/terminal-app.c
- src/terminal.c
test: disable smclient
```
$ ./autogen.sh --prefix=/usr --enable-compile-warnings=maximum --enable-debug --disable-smclient
$ make &> make.log && sudo make install
```
> build: Isolate smclient

- src/terminal-screen.c
- src/terminal-window.c
- src/terminal.c
Now it can run both X11 and wayland.
> Enable wayland support

- README
Use of submodule implies some commands before a compilation attempt.
> Add compilation help

- src/terminal-window.c
Prevent double-clicking on terminal contents while certain in-terminal apps such as htop are
running from invoking the tab rename dialog meant to be triggered by double-clicking on the tab's header
> Tabs: only invoke naming dialog to doubleclick on tab header
